### PR TITLE
Update for 115

### PR DESCRIPTION
**Pull request by jobisoft**
Minimal changes required for TB115. To reduce maintenance work, dropped support for TB91.

### CODE REVIEW

**Comment by jobisoft** [comment]
Services is a global object and does not need to be imported. The call will actually fail in TB117 or TB118. It is not needed since TB91.

**Comment by tatankat** [comment]
Thanks for the info and many thanks for the update! (a newer linter doesn't give this error anymore)

May I ask you to shine a light on the issue where resizing the sidepane is broken and the comment on the fact that customui will never make it in the core API: https://github.com/ganast/tidybird/issues/96 ?

**Comment by jobisoft** [comment]
We still pursue a sidebar, but it will be as part of the mailtabs API or a dedicated sidebar API. But I think we will not impmement a general custom UI API which aims to cover multiple different areas.

I currently have no info on the resident issue.

**Comment by tatankat** [comment]
Ok, I understand. I consider this good news :)
Happy to test the new API once it's available.

**Pull request merged**
