### PR TITLE
Compatibility Update for Thunderbird 128

### PR DESCRIPTION
**Pull request by jobisoft**
This update removes the tidybird API and replaces it by browser.folders.query({recent}).

The custom_ui API still works, but it is no longer possible to get the `gridTemplate` from the loaded style sheets. Instead, we fall back to `getComputedstyle`.

### CODE REVIEW

**Comment by MBS17** [comment]
Hi, I'm a regular user, and want to know if there will be an official update to Thunderbird 128, or if we need to do it ourselves... If that's the second case, is there a step by step guide to do so? Thanks.

**Comment by jobisoft** [comment]
> Hi, I'm a regular user, and want to know if there will be an official update to Thunderbird 128, or if we need to do it ourselves... If that's the second case, is there a step by step guide to do so? Thanks.

[tidybird-4.7.zip](https://github.com/user-attachments/files/16687657/tidybird-4.7.zip)

1. Download the zip file linked above (no need to unpack it)
2. Open Thunderbird and open the Add-on Manger
3. Click on th gear icon and select "install from file"
4. select the downloaded zip file

**Comment by MBS17** [comment]
Wonderful, it worked, thanks!

**Comment by barryburd** [comment]
Thank you.

**Comment by hinkis** [comment]
I would also be very happy for a correction
 Bug.
When I change folders, I lose all columns except the message list and it jumps to the right.

**Comment by LongChair** [comment]
I am still having wierd behavior when browsing folders. The tidybird panel goes away and so does the folder list.
I have to desactivate the addon to recover a usable state.
Hopefully we'll get a fix soon :)

**Comment by LongChair** [comment]
To be a bit more specific about the behavior i have.
Once i have installed from the zip above, it looks okay.
But then if i click on any folder in the folders pnael, the UI goes crazy:
 - The Tidybrid panel which i have on right pane disapears
 - The folder pane on the left looks blank

if i click again on the tidybird button at the top right of the TB bar, it will recover the folder list on the left and put the tidybird bar on the right but it's empty (no folder buttons).
clicking again on teh same button will toggle between the two situation (empty pane moving on left over folders, to moving to right).

@jobisoft any clue on what is happenning ? ;)

**Comment by hinkis** [comment]
Sorry but I didn't understand where is the updated version? Thank you very much

**Comment by tatankat** [comment]
There is already an official update, so your add-on should automatically update.
If it does not, check this: https://support.mozilla.org/en-US/kb/thunderbird-add-ons-frequently-asked-questions#w_how-do-i-update-an-add-on-manually

**Comment by hinkis** [comment]
really thanks

**Pull request merged**
